image: docker:latest

services:
  - docker:dind

stages:
  - build

build_image:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE/php-apache-image" .
    - docker push "$CI_REGISTRY_IMAGE/php-apache-image"
